eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  datasource:
    #url: jdbc:mysql://localhost:3307/userdb
    url: jdbc:mysql://mysql-db.ci6oicgtfzld.eu-west-2.rds.amazonaws.com:3306/userdb
    password: rootroot
    username: root
